# Generated by Django 5.0.6 on 2024-05-12 02:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('literals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marital_status', models.CharField(choices=[('married', 'Married'), ('single', 'Single'), ('divorced', 'Divorced'), ('separated', 'Separate')], default='single', max_length=20)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('other_name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('secondary_phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('baptismal_date', models.DateField(blank=True, null=True)),
                ('digital_address', models.CharField(blank=True, help_text='House or digital address', max_length=200, null=True)),
                ('profile', models.ImageField(blank=True, null=True, upload_to='')),
                ('occupation', models.CharField(blank=True, max_length=200, null=True)),
                ('place_of_work', models.CharField(blank=True, max_length=200, null=True)),
                ('unique_id', models.CharField(max_length=200)),
                ('group', models.ManyToManyField(to='literals.group')),
                ('location', models.ForeignKey(help_text='Location or Residencial area', on_delete=django.db.models.deletion.PROTECT, to='literals.location')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='literals.status')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
