# Generated by Django 5.0.6 on 2024-05-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='unique_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
