# Generated by Django 5.0.6 on 2024-05-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literals', '0001_initial'),
        ('members', '0002_alter_member_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='group',
            field=models.ManyToManyField(blank=True, to='literals.group'),
        ),
    ]
