# Generated by Django 5.0.6 on 2024-08-29 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_gender_alter_member_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='number_of_children',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
